# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-29 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fondos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bellasartes',
            name='adquirido',
        ),
        migrations.RemoveField(
            model_name='bellasartes',
            name='contexto',
        ),
        migrations.RemoveField(
            model_name='objeto',
            name='exposicion',
        ),
        migrations.RemoveField(
            model_name='objeto',
            name='propietario',
        ),
        migrations.AddField(
            model_name='bellasartes',
            name='formaingreso',
            field=models.CharField(choices=[('Compra', 'Compra'), ('Donacion', 'Donacion'), ('Legado', 'Legado')], default='1', max_length=8, verbose_name='Forma de ingreso'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='codigo',
            field=models.CharField(choices=[('DJ', 'DJ'), ('CE', 'CE'), ('DO', 'DO'), ('DE', 'DE')], default='DJ', max_length=2, verbose_name='C\xf3digo'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='observaciones',
            field=models.TextField(default='No'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informeintervencion',
            name='justificacion',
            field=models.TextField(verbose_name='Justificaci\xf3n de la intervencion'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='altura',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Altura en cm'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='ancho',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ancho en cm'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='sala',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nombre de la ubicacion'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='siglo_desde',
            field=models.CharField(max_length=4, verbose_name='Desde siglo'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='siglo_hasta',
            field=models.CharField(max_length=4, verbose_name='Hasta siglo'),
        ),
        migrations.DeleteModel(
            name='Contexto',
        ),
    ]
