# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-02 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fondos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='foto',
            field=models.ImageField(default='nofoto.png', upload_to='/autores/'),
        ),
    ]
