# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-02 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fondos', '0002_auto_20170602_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='foto',
            field=models.ImageField(default='nofoto.png', upload_to='autores'),
        ),
    ]
