# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 11:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.TextField(default=None)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('Por aprobar', 'Por aprobar'), ('Aprobado', 'Aprobado'), ('Cerrado', 'Cerrado'), ('No es bug', 'No es bug'), ('No arreglado', 'No arreglado')], default='Por aprobar', max_length=30)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('gravedad', models.IntegerField()),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['creado_el'],
                'verbose_name_plural': 'Incidencias',
            },
        ),
    ]
