# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-06 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(default=None, max_length=40)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('Por aprobar', 'Por aprobar'), ('Aprobado', 'Aprobado'), ('Cerrado', 'Cerrado'), ('No es bug', 'No es bug'), ('No arreglado', 'No arreglado')], default='Por aprobar', max_length=10)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
