# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-06 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='asunto',
            field=models.TextField(default=None),
        ),
    ]
