# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-06 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bug', '0003_auto_20170606_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='gravedad',
            field=models.IntegerField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='propietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
