# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-06 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0004_auto_20170606_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='gravedad',
            field=models.IntegerField(),
        ),
    ]
