# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0005_auto_20170606_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['creado_el'], 'verbose_name_plural': 'Incidencias'},
        ),
    ]
